"""add_premium_features

Revision ID: 0a3742cd0a88
Revises: a10d137d4bee
Create Date: 2026-05-06 23:40:42.056308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a3742cd0a88'
down_revision: Union[str, Sequence[str], None] = 'a10d137d4bee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AsignacionProfesional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('id_profesional', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_paciente'], ['Usuario.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_profesional'], ['Usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_AsignacionProfesional_id'), 'AsignacionProfesional', ['id'], unique=False)
    op.create_table('TransaccionMock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_TransaccionMock_id'), 'TransaccionMock', ['id'], unique=False)
    op.add_column('Evaluacion', sa.Column('has_high_risk', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Evaluacion', 'has_high_risk')
    op.drop_index(op.f('ix_TransaccionMock_id'), table_name='TransaccionMock')
    op.drop_table('TransaccionMock')
    op.drop_index(op.f('ix_AsignacionProfesional_id'), table_name='AsignacionProfesional')
    op.drop_table('AsignacionProfesional')
    # ### end Alembic commands ###
