"""Initial Migration

Revision ID: 44378312da06
Revises:
Create Date: 2026-06-01 20:03:38.084907

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '44378312da06'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Cuestionario',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo_cuestionario', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=True),
    sa.Column('twoFactorEnabled', sa.Boolean(), nullable=True),
    sa.Column('colegiatura', sa.String(length=50), nullable=True),
    sa.Column('especialidad', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Usuario_email'), 'Usuario', ['email'], unique=True)
    op.create_index(op.f('ix_Usuario_id'), 'Usuario', ['id'], unique=False)
    op.create_table('AsignacionProfesional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('id_profesional', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_paciente'], ['Usuario.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_profesional'], ['Usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_AsignacionProfesional_id'), 'AsignacionProfesional', ['id'], unique=False)
    op.create_table('Cita',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('id_profesional', sa.Integer(), nullable=False),
    sa.Column('fecha_cita', sa.DateTime(), nullable=False),
    sa.Column('link_reunion', sa.String(length=255), nullable=True),
    sa.Column('mensaje_seguimiento', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_paciente'], ['Usuario.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_profesional'], ['Usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Cita_id'), 'Cita', ['id'], unique=False)
    op.create_table('Evaluacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('phq9Score', sa.Integer(), nullable=True),
    sa.Column('gad7Score', sa.Integer(), nullable=True),
    sa.Column('nivelRiesgo', sa.String(length=50), nullable=True),
    sa.Column('resultadoIA', sa.Text(), nullable=True),
    sa.Column('notas_personales', sa.Text(), nullable=True),
    sa.Column('has_high_risk', sa.Boolean(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Evaluacion_id'), 'Evaluacion', ['id'], unique=False)
    op.create_table('Recurso',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=True),
    sa.Column('id_usuario_administrador', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario_administrador'], ['Usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('RegistroEmocional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('emocion_principal', sa.String(length=50), nullable=True),
    sa.Column('intensidad', sa.Integer(), nullable=True),
    sa.Column('disparador', sa.String(length=200), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_RegistroEmocional_id'), 'RegistroEmocional', ['id'], unique=False)
    op.create_table('TransaccionMock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_profesional', sa.Integer(), nullable=True),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('metodo_pago', sa.String(length=50), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_profesional'], ['Usuario.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_TransaccionMock_id'), 'TransaccionMock', ['id'], unique=False)
    op.create_table('ResultadoIA',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nivel', sa.String(length=10), nullable=True),
    sa.Column('scoreConfianza', sa.Float(), nullable=True),
    sa.Column('id_evaluacion', sa.Integer(), nullable=True),
    sa.CheckConstraint("nivel IN ('BAJO', 'MEDIO', 'ALTO')", name='check_nivel'),
    sa.ForeignKeyConstraint(['id_evaluacion'], ['Evaluacion.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_evaluacion')
    )
    op.create_index(op.f('ix_ResultadoIA_id'), 'ResultadoIA', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ResultadoIA_id'), table_name='ResultadoIA')
    op.drop_table('ResultadoIA')
    op.drop_index(op.f('ix_TransaccionMock_id'), table_name='TransaccionMock')
    op.drop_table('TransaccionMock')
    op.drop_index(op.f('ix_RegistroEmocional_id'), table_name='RegistroEmocional')
    op.drop_table('RegistroEmocional')
    op.drop_table('Recurso')
    op.drop_index(op.f('ix_Evaluacion_id'), table_name='Evaluacion')
    op.drop_table('Evaluacion')
    op.drop_index(op.f('ix_Cita_id'), table_name='Cita')
    op.drop_table('Cita')
    op.drop_index(op.f('ix_AsignacionProfesional_id'), table_name='AsignacionProfesional')
    op.drop_table('AsignacionProfesional')
    op.drop_index(op.f('ix_Usuario_id'), table_name='Usuario')
    op.drop_index(op.f('ix_Usuario_email'), table_name='Usuario')
    op.drop_table('Usuario')
    op.drop_table('Cuestionario')
    # ### end Alembic commands ###
