"""Add emotional fields

Revision ID: a10d137d4bee
Revises: 1d30d33a3d60
Create Date: 2026-04-27 16:14:47.503646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a10d137d4bee'
down_revision: Union[str, Sequence[str], None] = '1d30d33a3d60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RegistroEmocional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('emocion_principal', sa.String(length=50), nullable=True),
    sa.Column('intensidad', sa.Integer(), nullable=True),
    sa.Column('disparador', sa.String(length=200), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_RegistroEmocional_id'), 'RegistroEmocional', ['id'], unique=False)
    op.add_column('Evaluacion', sa.Column('notas_personales', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Evaluacion', 'notas_personales')
    op.drop_index(op.f('ix_RegistroEmocional_id'), table_name='RegistroEmocional')
    op.drop_table('RegistroEmocional')
    # ### end Alembic commands ###
